---
:verbose: false
:concurrency: 2
:timeout: 120
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - wx_critical
  - wx_default

staging:
  :concurrency: 3
production:
  :concurrency: 20
