:concurrency: 5
# 相对目录，启动时工作目录须为项目根目录
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:daemon: false
:environment: production

:queues:
    - default
    - [video, 2]
    - [mailers, 2]

development:
  :concurrency: 5
production:
  :concurrency: <%= ENV['SERVER_TYPE'] == 'development' ? 5 : 20 %>

